// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SqlBusMsg.proto

package com.github.bingoohuang.sqlbus.proto;

public final class SqlBusMsg {
  private SqlBusMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SqlBusEventMsgReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string hostname = 1;</code>
     */
    boolean hasHostname();
    /**
     * <code>required string hostname = 1;</code>
     */
    java.lang.String getHostname();
    /**
     * <code>required string hostname = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostnameBytes();

    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>required string table = 3;</code>
     */
    boolean hasTable();
    /**
     * <code>required string table = 3;</code>
     */
    java.lang.String getTable();
    /**
     * <code>required string table = 3;</code>
     */
    com.google.protobuf.ByteString
        getTableBytes();

    /**
     * <code>required string sqlType = 4;</code>
     */
    boolean hasSqlType();
    /**
     * <code>required string sqlType = 4;</code>
     */
    java.lang.String getSqlType();
    /**
     * <code>required string sqlType = 4;</code>
     */
    com.google.protobuf.ByteString
        getSqlTypeBytes();

    /**
     * <code>required string sql = 5;</code>
     */
    boolean hasSql();
    /**
     * <code>required string sql = 5;</code>
     */
    java.lang.String getSql();
    /**
     * <code>required string sql = 5;</code>
     */
    com.google.protobuf.ByteString
        getSqlBytes();

    /**
     * <code>repeated string parameters = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getParametersList();
    /**
     * <code>repeated string parameters = 6;</code>
     */
    int getParametersCount();
    /**
     * <code>repeated string parameters = 6;</code>
     */
    java.lang.String getParameters(int index);
    /**
     * <code>repeated string parameters = 6;</code>
     */
    com.google.protobuf.ByteString
        getParametersBytes(int index);
  }
  /**
   * Protobuf type {@code com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq}
   */
  public static final class SqlBusEventMsgReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq)
      SqlBusEventMsgReqOrBuilder {
    // Use SqlBusEventMsgReq.newBuilder() to construct.
    private SqlBusEventMsgReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SqlBusEventMsgReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SqlBusEventMsgReq defaultInstance;
    public static SqlBusEventMsgReq getDefaultInstance() {
      return defaultInstance;
    }

    public SqlBusEventMsgReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SqlBusEventMsgReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              hostname_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              table_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sqlType_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sql_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                parameters_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              parameters_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          parameters_ = parameters_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.class, com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.Builder.class);
    }

    public static com.google.protobuf.Parser<SqlBusEventMsgReq> PARSER =
        new com.google.protobuf.AbstractParser<SqlBusEventMsgReq>() {
      public SqlBusEventMsgReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SqlBusEventMsgReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SqlBusEventMsgReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object hostname_;
    /**
     * <code>required string hostname = 1;</code>
     */
    public boolean hasHostname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string hostname = 1;</code>
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hostname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string hostname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TABLE_FIELD_NUMBER = 3;
    private java.lang.Object table_;
    /**
     * <code>required string table = 3;</code>
     */
    public boolean hasTable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string table = 3;</code>
     */
    public java.lang.String getTable() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          table_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string table = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTableBytes() {
      java.lang.Object ref = table_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        table_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SQLTYPE_FIELD_NUMBER = 4;
    private java.lang.Object sqlType_;
    /**
     * <code>required string sqlType = 4;</code>
     */
    public boolean hasSqlType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string sqlType = 4;</code>
     */
    public java.lang.String getSqlType() {
      java.lang.Object ref = sqlType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sqlType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sqlType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSqlTypeBytes() {
      java.lang.Object ref = sqlType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SQL_FIELD_NUMBER = 5;
    private java.lang.Object sql_;
    /**
     * <code>required string sql = 5;</code>
     */
    public boolean hasSql() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string sql = 5;</code>
     */
    public java.lang.String getSql() {
      java.lang.Object ref = sql_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sql_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sql = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSqlBytes() {
      java.lang.Object ref = sql_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sql_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList parameters_;
    /**
     * <code>repeated string parameters = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated string parameters = 6;</code>
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated string parameters = 6;</code>
     */
    public java.lang.String getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated string parameters = 6;</code>
     */
    public com.google.protobuf.ByteString
        getParametersBytes(int index) {
      return parameters_.getByteString(index);
    }

    private void initFields() {
      hostname_ = "";
      timestamp_ = 0L;
      table_ = "";
      sqlType_ = "";
      sql_ = "";
      parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHostname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSqlType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSql()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSqlTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSqlBytes());
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeBytes(6, parameters_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTableBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSqlTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSqlBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameters_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq)
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.class, com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.Builder.class);
      }

      // Construct using com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hostname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        table_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sqlType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sql_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor;
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq getDefaultInstanceForType() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.getDefaultInstance();
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq build() {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq buildPartial() {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq result = new com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostname_ = hostname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.table_ = table_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sqlType_ = sqlType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sql_ = sql_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          parameters_ = parameters_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.parameters_ = parameters_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq) {
          return mergeFrom((com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq other) {
        if (other == com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq.getDefaultInstance()) return this;
        if (other.hasHostname()) {
          bitField0_ |= 0x00000001;
          hostname_ = other.hostname_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasTable()) {
          bitField0_ |= 0x00000004;
          table_ = other.table_;
          onChanged();
        }
        if (other.hasSqlType()) {
          bitField0_ |= 0x00000008;
          sqlType_ = other.sqlType_;
          onChanged();
        }
        if (other.hasSql()) {
          bitField0_ |= 0x00000010;
          sql_ = other.sql_;
          onChanged();
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHostname()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasTable()) {
          
          return false;
        }
        if (!hasSqlType()) {
          
          return false;
        }
        if (!hasSql()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object hostname_ = "";
      /**
       * <code>required string hostname = 1;</code>
       */
      public boolean hasHostname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public java.lang.String getHostname() {
        java.lang.Object ref = hostname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hostname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostnameBytes() {
        java.lang.Object ref = hostname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder setHostname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder clearHostname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostname_ = getDefaultInstance().getHostname();
        onChanged();
        return this;
      }
      /**
       * <code>required string hostname = 1;</code>
       */
      public Builder setHostnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hostname_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object table_ = "";
      /**
       * <code>required string table = 3;</code>
       */
      public boolean hasTable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string table = 3;</code>
       */
      public java.lang.String getTable() {
        java.lang.Object ref = table_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            table_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string table = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTableBytes() {
        java.lang.Object ref = table_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          table_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string table = 3;</code>
       */
      public Builder setTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        table_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string table = 3;</code>
       */
      public Builder clearTable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        table_ = getDefaultInstance().getTable();
        onChanged();
        return this;
      }
      /**
       * <code>required string table = 3;</code>
       */
      public Builder setTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        table_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sqlType_ = "";
      /**
       * <code>required string sqlType = 4;</code>
       */
      public boolean hasSqlType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string sqlType = 4;</code>
       */
      public java.lang.String getSqlType() {
        java.lang.Object ref = sqlType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sqlType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sqlType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSqlTypeBytes() {
        java.lang.Object ref = sqlType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sqlType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sqlType = 4;</code>
       */
      public Builder setSqlType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sqlType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlType = 4;</code>
       */
      public Builder clearSqlType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sqlType_ = getDefaultInstance().getSqlType();
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlType = 4;</code>
       */
      public Builder setSqlTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sqlType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sql_ = "";
      /**
       * <code>required string sql = 5;</code>
       */
      public boolean hasSql() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string sql = 5;</code>
       */
      public java.lang.String getSql() {
        java.lang.Object ref = sql_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sql_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sql = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSqlBytes() {
        java.lang.Object ref = sql_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sql_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sql = 5;</code>
       */
      public Builder setSql(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sql_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sql = 5;</code>
       */
      public Builder clearSql() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sql_ = getDefaultInstance().getSql();
        onChanged();
        return this;
      }
      /**
       * <code>required string sql = 5;</code>
       */
      public Builder setSqlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sql_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          parameters_ = new com.google.protobuf.LazyStringArrayList(parameters_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParametersList() {
        return parameters_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public int getParametersCount() {
        return parameters_.size();
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public java.lang.String getParameters(int index) {
        return parameters_.get(index);
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public com.google.protobuf.ByteString
          getParametersBytes(int index) {
        return parameters_.getByteString(index);
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public Builder setParameters(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public Builder addParameters(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public Builder addAllParameters(
          java.lang.Iterable<java.lang.String> values) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public Builder clearParameters() {
        parameters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameters = 6;</code>
       */
      public Builder addParametersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq)
    }

    static {
      defaultInstance = new SqlBusEventMsgReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgReq)
  }

  public interface SqlBusEventMsgRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp}
   */
  public static final class SqlBusEventMsgRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp)
      SqlBusEventMsgRspOrBuilder {
    // Use SqlBusEventMsgRsp.newBuilder() to construct.
    private SqlBusEventMsgRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SqlBusEventMsgRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SqlBusEventMsgRsp defaultInstance;
    public static SqlBusEventMsgRsp getDefaultInstance() {
      return defaultInstance;
    }

    public SqlBusEventMsgRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SqlBusEventMsgRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.class, com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<SqlBusEventMsgRsp> PARSER =
        new com.google.protobuf.AbstractParser<SqlBusEventMsgRsp>() {
      public SqlBusEventMsgRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SqlBusEventMsgRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SqlBusEventMsgRsp> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp)
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.class, com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.Builder.class);
      }

      // Construct using com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor;
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp getDefaultInstanceForType() {
        return com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.getDefaultInstance();
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp build() {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp buildPartial() {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp result = new com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp) {
          return mergeFrom((com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp other) {
        if (other == com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.bingoohuang.sqlbus.proto.SqlBusMsg.SqlBusEventMsgRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp)
    }

    static {
      defaultInstance = new SqlBusEventMsgRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.github.bingoohuang.sqlbus.proto.SqlBusEventMsgRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SqlBusMsg.proto\022#com.github.bingoohuan" +
      "g.sqlbus.proto\"y\n\021SqlBusEventMsgReq\022\020\n\010h" +
      "ostname\030\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\004\022\r\n\005tabl" +
      "e\030\003 \002(\t\022\017\n\007sqlType\030\004 \002(\t\022\013\n\003sql\030\005 \002(\t\022\022\n" +
      "\nparameters\030\006 \003(\t\"\023\n\021SqlBusEventMsgRspB0" +
      "\n#com.github.bingoohuang.sqlbus.protoB\tS" +
      "qlBusMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgReq_descriptor,
        new java.lang.String[] { "Hostname", "Timestamp", "Table", "SqlType", "Sql", "Parameters", });
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_github_bingoohuang_sqlbus_proto_SqlBusEventMsgRsp_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
